import Head from "next/head";
import Link from "next/link";
import React, { useState } from "react";
import { api } from "~/utils/api";
import Image from "next/image";

interface LayoutProps {
  children: React.ReactNode;
}

const Layout: React.FC<LayoutProps> = ({ children }) => {
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  const handleClick = () => {
    setIsMenuOpen(!isMenuOpen);
  };

  return (
    <>
      <Head>
        <title>Mittwatt</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
      </Head>
      <main>
        <header>
          <nav className="sticky top-0 flex bg-gradient-to-r from-green-800 to-green-600">
            <div className="flex items-center gap-2 p-2">
              <Link
                href="/"
                className="flex items-center text-2xl font-bold text-white"
              >
                <Image
                  src={"/images/logo.png"}
                  width={50}
                  height={50}
                  alt="Mittwatt"
                />
                <div className="text-2xl font-bold">
                  Mitt<span className="text-green-200">Watt</span>
                </div>
              </Link>
            </div>
            <div className="my-auto ml-auto block cursor-pointer pr-4 text-white md:hidden">
              <button
                id="mobile-menu-button"
                className="group peer"
                onClick={handleClick}
                aria-label="Toggle Menu"
              >
                <div
                  className={`h-1 w-8 rounded-full bg-zinc-200 transition-all ${isMenuOpen ? "relative top-2 rotate-45" : ""}`}
                ></div>
                <div
                  className={`mt-1 h-1 w-8 rounded-full bg-zinc-200 transition-all ${isMenuOpen ? "opacity-0" : "opacity-100"}`}
                ></div>
                <div
                  className={`mt-1 h-1 w-8 rounded-full bg-zinc-200 transition-all ${isMenuOpen ? "relative -top-2 -rotate-45" : ""}`}
                ></div>
              </button>
              <div
                className={`absolute right-0 top-16 min-h-screen w-5/6 transform bg-green-200 transition-transform ${isMenuOpen ? "translate-x-0" : "hidden translate-x-full"}`}
              >
                <Link
                  href="/"
                  className="flex cursor-pointer items-center justify-center p-4 font-bold text-black transition-colors hover:bg-green-200 hover:text-green-800"
                >
                  Home
                </Link>
                <Link
                  href="/current"
                  className="flex cursor-pointer items-center justify-center p-4 font-bold text-black transition-colors hover:bg-green-200 hover:text-green-800"
                >
                  Current
                </Link>
                <Link
                  href="/future"
                  className="flex cursor-pointer items-center justify-center p-4 font-bold text-black transition-colors hover:bg-green-200 hover:text-green-800"
                >
                  Future
                </Link>
                <Link
                  href="/past"
                  className="flex cursor-pointer items-center justify-center p-4 font-bold text-black transition-colors hover:bg-green-200 hover:text-green-800"
                >
                  Past
                </Link>
              </div>
            </div>

            <div className="hidden flex-1 items-center justify-end text-white md:flex">
              <Link
                href="/"
                className="flex h-full items-center p-4 font-bold transition-colors ease-in-out hover:bg-white/10 hover:text-green-100"
              >
                Home
              </Link>
              <Link
                href="/current"
                className="flex h-full items-center p-4 font-bold transition-colors ease-in-out hover:bg-white/10 hover:text-green-100"
              >
                Current
              </Link>
              <Link
                href="/future"
                className="flex h-full items-center p-4 font-bold transition-colors ease-in-out hover:bg-white/10 hover:text-green-100"
              >
                Future
              </Link>
              <Link
                href="/past"
                className="flex h-full items-center p-4 font-bold transition-colors ease-in-out hover:bg-white/10 hover:text-green-100"
              >
                Past
              </Link>
            </div>
          </nav>
        </header>

        <div className="flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-center text-5xl font-extrabold tracking-tight text-black sm:text-[5rem]">
            Welcome to <span className="text-green-500">Mitt</span>
            <span className="text-green-600">Watt</span> App
          </h1>

          {children}
        </div>
      </main>
    </>
  );
};

export default Layout;
